### ISSUE TITLE
Error on Redmine v 3.3.0

### ISSUE THREAD

**Issue by skoropadskiy** [mikitex70/redmine_drawio#1]
Redmine::PluginRequirementError: redmine_drawio plugin requires a Redmine version between 2.6 and 3.2 but current is 3.3.0.stable
/opt/redmine-3.3.0/lib/redmine/plugin.rb:220:in `block in requires_redmine'
/opt/redmine-3.3.0/lib/redmine/plugin.rb:205:in `each'
/opt/redmine-3.3.0/lib/redmine/plugin.rb:205:in `requires_redmine'
/opt/redmine-3.3.0/plugins/redmine_drawio/init.rb:14:in `block in <top (required)>'
/opt/redmine-3.3.0/lib/redmine/plugin.rb:75:in `instance_eval'
/opt/redmine-3.3.0/lib/redmine/plugin.rb:75:in `register'
/opt/redmine-3.3.0/plugins/redmine_drawio/init.rb:6:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine-3.3.0/lib/redmine/plugin.rb:155:in `block in load'
/opt/redmine-3.3.0/lib/redmine/plugin.rb:146:in `each'
/opt/redmine-3.3.0/lib/redmine/plugin.rb:146:in `load'
/opt/redmine-3.3.0/config/initializers/30-redmine.rb:21:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/opt/redmine-3.3.0/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by skoropadskiy** [comment]
Thanks a lot!
