### ISSUE TITLE
could not load drawio

### ISSUE THREAD

**Issue by archonwang** [mikitex70/redmine_drawio#37]
@mikitex70 , please check it.
Environment:
```
  Redmine version                3.3.4.stable.16766
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

error log
```
Started GET "/plugin_assets/redmine_drawio/javascripts/lang/drawio_jstoolbar-zh.js" for 192.168.20.253 at 2017-07-10 10:37:52 +0800

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_drawio/javascripts/lang/drawio_jstoolbar-zh.js"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  thin (1.7.0) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.7.0) lib/thin/connection.rb:84:in `catch'
  thin (1.7.0) lib/thin/connection.rb:84:in `pre_process'
  thin (1.7.0) lib/thin/connection.rb:50:in `block in process'
  eventmachine (1.2.3) lib/eventmachine.rb:1076:in `call'
  eventmachine (1.2.3) lib/eventmachine.rb:1076:in `block in spawn_threadpool'

```

**Comment by mikitex70** [comment]
Sorry, I've missed a couple of files.
I will commit them this evening.

**Comment by mikitex70** [comment]
Hi archonwang, I've committed the missing file but messages are in English.
Can you translate them?
Take also a look to the file ``config/locales/zh.yml``, there are two new messages that needs to be translated.
Thanks in advance.

**Comment by archonwang** [comment]
@mikitex70 ,
OK, I will check it. Thanks.

**Comment by archonwang** [comment]
@mikitex70 
please check the pull request: 
https://github.com/mikitex70/redmine_drawio/pull/38

**Comment by mikitex70** [comment]
Closing bug as fix has been merged into master branch.
