### ISSUE TITLE
Can't save diagramm

### ISSUE THREAD

**Issue by TomyDMG** [mikitex70/redmine_drawio#42]
Hi, I faced with srange problem. 
When I finished editing the image and press the save button, I get an error: 
![screenshot_15](https://user-images.githubusercontent.com/11715695/28922073-67cfb4e2-7861-11e7-9ba7-b1d9a23077bc.png)
But I use drawio_attach macro. Please help, if you have time.

Enviroment:
```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.1.0-p0 (2013-12-25) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```
Error log:

```
Started GET "/projects/tr-7/wiki/%d0%90%d1%80%d1%85%d0%b8%d1%82%d0%b5%d0%ba%d1%82%d1%83%d1%80%d0%b0_%d0%9f%d0%9e/%d0%90%d1%80%d1%85%d0%b8%d1%82%d0%b5%d0%ba%d1%82%d1%83%d1%80%d0%b0_%d0%9f%d0%9e.json?include=journals" for 212.116.102.34 at 2017-08-03 13:13:43 +0300

ActionController::RoutingError (No route matches [GET] "/projects/tr-7/wiki/%D0%90%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%B0_%D0%9F%D0%9E/%D0%90%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%B0_%D0%9F%D0%9E.json"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  passenger (4.0.38) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.38) lib/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
  passenger (4.0.38) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (4.0.38) lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'
```

**Comment by mikitex70** [comment]
The error message is generated by an HTTP 404 error (I need to distinguish errors generated by DMSF and by attachments so a more clear message can be shown).
During the post of the wiki body (to update the attachment name) the page was not found.
I think this is caused by the character encoding of the name of the wiki page: from your log it seems to be `Архитектура_ПО/Архитектура_ПО`.
As a workaround try to rename the page (the page, not the title) using standard ASCII characters, and it should work.
In the meantime I will check if this is a limitation of my code (and then correct it) or it is a limitation of Redmine REST API.

**Comment by TomyDMG** [comment]
You are right. An error occurs if there are non-English characters present in the wiki's URL.
