### ISSUE TITLE
Undefined method `alias_method_chain' for Redmine::WikiFormatting::Textile::Helper:Module

### ISSUE THREAD

**Issue by Dambuster88** [mikitex70/redmine_drawio#44]
Just cloned the repo, restart the nginx and I got an error:

```
Message from application: undefined method `alias_method_chain' for Redmine::WikiFormatting::Textile::Helper:Module
Did you mean?  alias_method (NoMethodError)
  /var/www/redmine/plugins/redmine_drawio/lib/redmine_drawio/helpers/textile_helper.rb:18:in `<module:Helper>'
  /var/www/redmine/plugins/redmine_drawio/lib/redmine_drawio/helpers/textile_helper.rb:4:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
  /var/www/redmine/plugins/redmine_drawio/lib/redmine_drawio.rb:10:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:379:in `block in require_or_load'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:36:in `block in load_interlock'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:36:in `load_interlock'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:357:in `require_or_load'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:335:in `depend_on'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:251:in `require_dependency'
  /var/www/redmine/plugins/redmine_drawio/after_init.rb:2:in `<top (required)>'
  /var/www/redmine/plugins/redmine_drawio/init.rb:21:in `require_relative'
  /var/www/redmine/plugins/redmine_drawio/init.rb:21:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
  /var/www/redmine/lib/redmine/plugin.rb:155:in `block in load'
  /var/www/redmine/lib/redmine/plugin.rb:146:in `each'
  /var/www/redmine/lib/redmine/plugin.rb:146:in `load'
  /var/www/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `block in load'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/engine.rb:655:in `block in load_config_initializer'
  /usr/local/rvm/gems/ruby-2.3.5/gems/activesupport-5.1.2/lib/active_support/notifications.rb:168:in `instrument'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/engine.rb:654:in `load_config_initializer'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/engine.rb:611:in `each'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/engine.rb:611:in `block in <class:Engine>'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:415:in `call'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
  /usr/local/rvm/gems/ruby-2.3.5/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
  /var/www/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.3.5/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.3.5/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```
```
Environment:
  Redmine version                3.4.3.devel
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  5.1.2
  Environment                    production
  Database adapter               PostgreSQL
```

**Comment by Dambuster88** [comment]
I think the problem is the use of `alias_method_chain` which is deprecated in the 5th version of Rails.
I have found a nice article [here](https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/) regarding this problem.

So, the problem seems to be in this [file](https://github.com/mikitex70/redmine_drawio/blob/1d2dbf75724acdcd5aff908c868a2f3259ea2fef/lib/redmine_drawio/helpers/textile_helper.rb)?

**Comment by Dambuster88** [comment]
Workaround:
In the [file](https://github.com/mikitex70/redmine_drawio/blob/1d2dbf75724acdcd5aff908c868a2f3259ea2fef/lib/redmine_drawio/helpers/textile_helper.rb), replace the line 6, from `heads_for_wiki_formatter_without_drawio` with `super` and remove or comment the line 18 which contain `alias_method_chain :heads_for_wiki_formatter, :drawio`.
For me is working now without any other modification to the code or to the server configuration;

**Comment by mikitex70** [comment]
Thanks for your suggestions @Dambuster88.
I haven't tested with Redmine 3.4, I hope to have time during Christmas holidays.
But you suggestions will simplify my work.
Thanks a lot.

**Comment by nanego** [comment]
Redmine 3.4 is only compatible with Rails 4.
You should not use Rails 5.1.2.

**Comment by mikitex70** [comment]
Thanks you @Dambuster88 for your suggestion.
I've applied your fix and tested with Redmine 3.4.2-stable, Ruby 2.3.4-p301 and Rails 4.2.8 (my containerized test environment) and works without troubles.
I need to test for older versions of Redmine (2.6, 3.0 and 3.1); maybe I will discard support for Redmine 2.6.
