### ISSUE TITLE
Plugin not working when `root` route is set to custom value

### ISSUE THREAD

**Issue by jallakim** [mikitex70/redmine_drawio#7]
Hi,

redmine_drawio doesn't seem to work if you have a custom value for your `root` route (in `config/routes.rb` within Redmine). Justification for changing the default `root` route is when you only have one project, and you'd like the "Home" button to go to that one project.

Original `root` route;
```
root :to => 'welcome#index', :as => 'home'
```

Our custom `root` route;
```
root :controller => 'projects', :action => 'show', :id => 'foobar', :as => 'home'
```

Error in `log/production.log` when going to the "Wiki" page;
```
Started GET "/projects/foobar/wiki" for fa80::1 at 2016-11-22 18:01:37 +0000
Processing by WikiController#show as HTML
  Parameters: {"project_id"=>"foobar"}
  Current user: foobar (id=1337)
  Rendered wiki/_content.html.erb (18.1ms)
  Rendered attachments/_form.html.erb (2.8ms)
  Rendered wiki/_sidebar.html.erb (2.6ms)
  Rendered wiki/show.html.erb within layouts/base (33.3ms)
Completed 500 Internal Server Error in 205ms (ActiveRecord: 84.8ms)

ActionView::Template::Error (No route matches {:action=>"index", :controller=>"welcome"}):
    120:   <div class="bgl"><div class="bgr">
    121:     Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2016 Jean-Philippe Lang
    122:   </div></div>
    123: </div>
    124: </div>
    125: </div>
    126: <%= call_hook :view_layouts_base_body_bottom %>
  plugins/redmine_drawio/lib/hooks/view_hooks.rb:29:in `redmine_url'
  plugins/redmine_drawio/lib/hooks/view_hooks.rb:17:in `view_layouts_base_body_bottom'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:123:in `_app_views_layouts_base_html_erb___1379630492326330453_66880840'
  app/controllers/wiki_controller.rb:119:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Running Redmine 3.3.1.devel with redmine_drawio 0.3.2 (cloned from git half an hour ago).

**Comment by jallakim** [comment]
It's working fine when reverting the `root` route to it's original value.

**Comment by mikitex70** [comment]
I've found the problem, now I need to find a workaround.
Be patient, maybe I will fix it in the weekend.

**Comment by jallakim** [comment]
Excellent! Don't stress -- it's kind of an "first world problem" problem :-P

**Comment by jallakim** [comment]
@mikitex70, excellent! Thanks!
